services:
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    # environment:
    #   - name=value
