name: Test and Deploy

on:
  push:
    branches: [ "main", "deploy"]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:

    runs-on: ubuntu-latest
    name: Test

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker Compose
      run: docker compose up -d
    - name: Reformat and flake8 Check
      run: docker compose exec backend sh -c "black -l 120 . && flake8 ."
    - name: Run Tests
      run: docker compose exec backend sh -c "pytest ."

  Deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: Test
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}

    steps:
    - uses: actions/checkout@v4
    - name: Connect to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: ls
